## 1.7 Introduction to Numpy

In [1]:
import numpy as np

### Arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
arr[2]=10

In [8]:
arr

array([ 1,  2, 10,  4,  5])

In [9]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multi-dimensional arrays

In [11]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
marr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [17]:
marr[:,2]

array([3, 6, 9])

In [18]:
marr[:,2]=[30,60,90]
marr

array([[ 1,  2, 30],
       [ 4,  5, 60],
       [ 7,  8, 90]])

### Randomly Generated Arrays

In [19]:
np.random.rand(5,2)

array([[0.19208785, 0.26351113],
       [0.01859562, 0.08370141],
       [0.81284332, 0.61891177],
       [0.18285811, 0.86142497],
       [0.55595996, 0.1467191 ]])

In [20]:
np.random.rand(5,2)

array([[0.01896996, 0.66176943],
       [0.66773195, 0.94140347],
       [0.67862126, 0.86625313],
       [0.82087407, 0.29223073],
       [0.33289474, 0.88126357]])

In [21]:
np.random.rand(5,2)

array([[0.47181029, 0.73777673],
       [0.0482814 , 0.77252494],
       [0.88558411, 0.40098752],
       [0.61143106, 0.22748472],
       [0.12344213, 0.19428909]])

- Lets fix the random generated numbers so that it matches for different users doing it on different computer by adding the SEED Function

In [24]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

### Element-wise operations

In [26]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [27]:
a+25

array([25, 26, 27, 28, 29])

In [28]:
b = (10 + (a*2))**2/100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [29]:
a > 2

array([False, False, False,  True,  True])

### Summarizing operations

In [30]:
a

array([0, 1, 2, 3, 4])

In [31]:
a.std()

np.float64(1.4142135623730951)

In [33]:
a.min()

np.int64(0)