## Linear Algebra Refresher

In [4]:
import numpy as np

## Vector

In [5]:
u = np.array([2,4,5,6])

In [6]:
10 * u

array([20, 40, 50, 60])

In [7]:
v = np.array([1,0,0,2])

In [8]:
v

array([1, 0, 0, 2])

In [9]:
u + v

array([3, 4, 5, 8])

In [10]:
u * v

array([ 2,  0,  0, 12])

## Multiplication

In [11]:
u.shape[0]

4

## Vector Vector Multiplication

In [12]:
def vec_vec_mult(u,v):
    assert u.shape[0] == v.shape[0]
    n = v.shape[0]
    result = 0.0
    for i in range(n):
        result += u[i] * v[i]
    return result

In [13]:
vec_vec_mult(u,v)

np.float64(14.0)

In [14]:
u.dot(v)

np.int64(14)

## Matrix-Vector Multiplication

In [15]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [16]:
def matrix_vector_mult(U,v):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]

    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vec_vec_mult(U[i],v)
    return result

In [17]:
matrix_vector_mult(U,v)

array([14.,  5.,  5.])

In [18]:
U.dot(v)

array([14,  5,  5])

## Matrix-Matrix Multiplication

In [19]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])

In [20]:
def matrix_matrix_mult(U,V):
    assert U.shape[1] == V.shape[0]
    
    num_cols = V.shape[1]
    num_rows = U.shape[0]

    result = np.zeros((num_rows, num_cols))
    
    for j in range(num_cols):
        vj = V[:,j]
        Uvj = matrix_vector_mult(U,vj)
        result[:,j] = Uvj

    return result
    
    

In [21]:
matrix_matrix_mult(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [22]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity Matrix

In [24]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse

In [26]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [28]:
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [30]:
Vinv = np.linalg.inv(Vs)
Vinv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [31]:
Vinv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
Vs.dot(Vinv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])